standalone trial of bokeh's async update code - the pattern is used in interact_sky() - to see if one could reproduce intermittent AttributeError: 'DocumentCallbackManager' object has no attribute '_change_callbacks' - (So far no success)